### ISSUE TITLE
Does Upbound Cloud support GCP?

### ISSUE THREAD

**Issue by echarles** [upbound/platform-ref-gcp#2]
https://cloud.upbound.io/docs/getting-started/configure-your-platform describes how to configure the platform for AWS and this worked for me. Kudos to Upbound/Crossplane team. I was able to deploy a VPC and a EKS in my AWS account via the Upbound Admin Console.

I have followed the same steps with `platform-ref-gcp`:

- deployed the platform-ref-gcp
- followed the instructions to create service account and get cred.json https://crossplane.io/docs/v1.0/getting-started/install-configure.html#select-provider
- deployed the provider config and secret

k get managed returns 

```

NAME                                              READY   SYNCED   STATE   ENDPOINT   LOCATION   AGE
gkecluster.container.gcp.crossplane.io/c1-6d2cp           False                       us-west2   15m

NAME                                            READY   SYNCED   STATE   CLUSTER-REF   AGE
nodepool.container.gcp.crossplane.io/c1-84m8p           False                          15m

NAME                                         READY   SYNCED
network.compute.gcp.crossplane.io/n1-ss65w           False

NAME                                            READY   SYNCED
subnetwork.compute.gcp.crossplane.io/n1-dx8nd           False
```

and the UI remains in not ready state.

Any advice to further debug my issue? Is GCP supported in current Upbound Cloud?

**Comment by jbw976** [comment]
Thanks for opening this issue @echarles and I'm sorry for the troubles you're hitting!

You are correct that the official Upbound Cloud docs focus on the step by step guide for getting started with the AWS reference platform, to give you a hands on example of the power of Upbound and Crossplane for building a reusable platform that enables self-service infrastructure provisioning.  The docs don't yet have the same in depth steps for this GCP reference platform, so it's a little bit behind in terms of its maturity.

The README here in this repo does have the steps, but not quite as pretty and polished as the official Upbound Cloud docs: https://github.com/upbound/platform-ref-gcp/blob/main/README.md

To look deeper into the state of your GCP objects here, I would run this to see what events are on the Network object.
```
kubectl describe network.compute.gcp.crossplane.io/n1-ss65w
```
I suspect something is wrong with the GCP ProviderConfig and/or its secret.  Feel free to also share what you can (being privacy/security minded of course) to dig deeper into what may be the issue with the ProviderConfig and/or secret.  Thanks @echarles!

**Comment by echarles** [comment]
@jbw976 Thx for the help. I have described a bit more the pods and realized that my `ProviderConfig.metadata.name` was not set to`default`. I have fixed that and have been a bit further towards the next issue which is 

```
Warning  CannotObserveExternalResource  10s (x9 over 3m41s)    managed/network.compute.gcp.crossplane.io  cannot get GCP network: googleapi: Error 403: Required 'compute.networks.get' permission for 'projects/.../global/networks/net1-...', forbidden
```

So I have enabled the Service Networking API in gcloud console, but it was still failing.

tried from scratch, and got the same error. I guess I need to add more permissions somewhere... but don't know where...

**Comment by grantgumina** [comment]
@echarles have you added these roles to the service account you're using in GCP? 

- roles/compute.networkAdmin
- roles/container.admin
- roles/iam.serviceAccountUser

**Comment by echarles** [comment]
After adding the roles @grantgumina has listed, GKE cluster is launching. Thx a bunch.

**Comment by grantgumina** [comment]
Sure thing! Glad to have helped!

**Comment by echarles** [comment]
Cluster has successfully started. Closing. Thx all for your help.
