### ISSUE TITLE
App devs can't trigger creation of networking for their cluster anymore

### ISSUE THREAD

**Issue by jbw976** [upbound/platform-ref-gcp#21]
As a follow-up to #19, we need SOME way for the creation of a cluster to also get its networking created.  Right now, if an app dev creates a Cluster claim, it won't have any networking (bad), and the app dev can't create the networking themselves because there's no networking claim (good).

We should update this platform-ref-gcp to follow the same pattern we see in platform-ref-aws and platform-ref-azure.

* https://github.com/upbound/platform-ref-azure/pull/3
* https://github.com/upbound/platform-ref-aws/pull/65

In that pattern, the networking resources essentially moved into the Cluster XR - so by creating a Cluster claim, all of its required networking will also be created.

**Comment by jbw976** [comment]
I would love for @elohmrow to take on this effort as part of his technical ramping up :)

**Comment by elohmrow** [comment]
@jbw976 maybe this should be put on hold? https://github.com/upbound/squad-customer-community/issues/46#issuecomment-1145073261

**Comment by ytsarev** [comment]
The desired pattern of embedding Network XR instantiation into the main Cluster Composition was implemented in #22 . Closing this one
