### ISSUE TITLE
New GKE cluster ends up in repairing state

### ISSUE THREAD

**Issue by ytsarev** [upbound/platform-ref-gcp#40]
### What happened?

<img width="815" alt="image" src="https://user-images.githubusercontent.com/518532/198578956-707c0398-de46-4985-9ea1-1d984e01739f.png">

Unexpected repairing of fresh GKE clusters created by this platform. 

This behavior was frequently encountered during uptesting of https://github.com/upbound/platform-ref-gcp/pull/39 

It created really long test runs waiting for the cluster to be available for e.g. deletion after the 'repairing' process

See also https://github.com/upbound/platform-ref-gcp/pull/22#issuecomment-1259626500

### How can we reproduce it?

/test-e2e

and observe the associated cluster behaviour 

### What environment did it happen in?

`universal-crossplane-1.9.1-up.2`
`xpkg.upbound.io/upbound/provider-gcp:v0.16.0`
`uptest v0.2.0`

**Comment by haarchri** [comment]
we don't see this issue anymore with: https://github.com/upbound/platform-ref-gcp/pull/49
